@startuml

class Type {
    + int id
    + String name
    + String description
}

class Day {
    + int id
    + String name
    + String description
}

class Rutine {
    + int id
    + String name
    + Type type
    + Day[] days
    + String hour
}

class Activity {
    + int id
    + String name
    + String description
    + int goal
    + string CurrentState # opcional
}

class ActivityStart {
    + int id
    + Date date
    + Activity Activity
}

class ActivityEnd {
    + int id
    + Date date
    + ActivityStart ActivityStart
    + int minutes
}

@enduml
